import React from "react";
import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * RootLayout wraps the app and provides a container for the client onboarding tool.
 */
const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  return (
    <html lang="en">
      <body className="bg-background text-foreground min-h-screen flex flex-col items-center justify-start p-8">
        <Toaster position="top-right" />
        <main className="w-full p-20">
          <h1 className="text-3xl font-bold mb-6 text-center">
            Client Onboarding
          </h1>
          {children}
        </main>
      </body>
    </html>
  );
};

export default RootLayout;
